apimServiceName: PRACTICE-APIM-PROD
namedValues:
  - name: commonutilities-backend-uri-key
    properties:
      displayName: commonutilities-backend-uri-key
      keyVault:
        secretIdentifier: "https://practice-kvault-prod.vault.azure.net/secrets/commonutilities-backend-uri-key"
  - name: commonutilities-backend-uri
    properties:
      displayName: commonutilities-backend-uri
      value: "/workflows/f9ed02c791d74149be5fb8be4ec1d005/triggers/When_a_HTTP_request_is_received/paths/invoke?api-version=2016-10-01\u0026sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun\u0026sv=1.0\u0026sig="
backends:
  - name: commonutilities-backend-url
    properties:
      url: "https://prod-43.eastus.logic.azure.com:443"
