 apiNames:
  - commonutilities-v1

 diagnosticNames:
  - ignore

 loggerNames:
  - ignore

 productNames:
  - ignore

 subscriptionNames:
  - ignore

 tagNames:
  - ignore

 groupNames:
  - ignore

 versionSetNames: 
  - 67f8c48c4c3f96a39ce6bb52

 namedValueNames:
  - commonutilities-backend-uri

 backendNames:
  - ignore

 policyFragmentNames:
  - ignore
