 apiNames:
  - commonutilities-v1
  - commonutilities-v2

 diagnosticNames:
  - ignore

 loggerNames:
  - ignore

 productNames:
  - ignore

 subscriptionNames:
  - ignore

 tagNames:
  - ignore

 groupNames:
  - ignore

 versionSetNames: 
  - ignore

 namedValueNames:
  - commonutilities-backend-uri
  - commonutilities-backend-uri-key

 backendNames:
  - commonutilities-backend-url

 policyFragmentNames:
  - ignore
