 apiNames:
  - commonutilities-v1

 diagnosticNames: []

 loggerNames: []

 productNames: []

 subscriptionNames: []

 tagNames: []

 groupNames: []

 versionSetNames: []

 namedValueNames:
  - commonutilities-backend-uri
  - commonutilities-backend-uri-key

 backendNames: 
  - commonutilities-backend-url

 policyFragmentNames: []
