 apiNames:
  - test-v1

 diagnosticNames:
  - ignore

 loggerNames:
  - ignore

 productNames:
  - ignore

 subscriptionNames:
  - ignore

 tagNames:
  - ignore

 groupNames:
  - ignore

 versionSetNames: 
  - 67fa2db02d4d22468283a063

 namedValueNames:
  - Environment

 backendNames:
  - ignore

 policyFragmentNames:
  - ignore
